### ISSUE TITLE
QUESTION 

### ISSUE THREAD

**Issue by drogit** [cakemanager/cakephp-users#5]
# QUESTION (not an "issue")

when they say 'not stable' does that mean does not install at all?  me a newbie to cake. despite days of hacker type efforts i have not been able to make it work!  the config is messed up somehow and never runs the plugin itself. not sure if anyone supporting it but just thought i whine about it a wee bit.  that admin plugin is awesome, works out of the box but this one not as newbie friendly.  this was a skeleton project with just users plugin.  newbie has surrendered and now back to using cakedc/users and no admin (dang!)

_Error: A route matching "array ( 'prefix' => false, 'plugin' => 'Users', 'controller' => 'Users', 'action' => 'login', '_ext' => NULL, )" could not be found._
### /debug_kit/toolbar/clear_cache  [ 'controller' => 'Toolbar', 'action' => 'clearCache', 'plugin' => 'DebugKit' ] [ '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'Cake\Routing\Route\Route' ]

/debug_kit/toolbar/\*    [ 'controller' => 'Requests', 'action' => 'view', 'plugin' => 'DebugKit' ]  [ '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'Cake\Routing\Route\Route' ]
/debug_kit/panels/view/\*    [ 'controller' => 'Panels', 'action' => 'view', 'plugin' => 'DebugKit' ]    [ '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'Cake\Routing\Route\Route' ]
/debug_kit/panels/\* [ 'controller' => 'Panels', 'action' => 'index', 'plugin' => 'DebugKit' ]   [ '_ext' => [ (int) 0 => 'json' ], 'routeClass' => 'Cake\Routing\Route\Route' ]
/   [ 'controller' => 'Pages', 'action' => 'display', (int) 0 => 'home', 'plugin' => null ] [ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/pages/\*    [ 'controller' => 'Pages', 'action' => 'display', 'plugin' => null ]    [ '_ext' => [], 'routeClass' => 'DashedRoute' ]
/:controller    [ 'action' => 'index', 'plugin' => null ]   [ 'routeClass' => 'DashedRoute', '_ext' => [] ]
/:controller/:action/\*  [ 'action' => 'index', 'plugin' => null ]   [ 'routeClass' => 'DashedRoute', '_ext' => [] ]

**Comment by drogit** [comment]
moved question to a more appropriate forum, sorry newbie.  i try and delete issue but cant?

**Comment by bobmulder** [comment]
Hi @drogit, is your question still relevant or can it be closed? Issues can't be deleted, they only can be closed... Let me know!

**Comment by drogit** [comment]
ok buddy. newbie sorry he made an "issue" out of it!  to answer your query NO. I was unable to resolve the issue. no cake experience (yet). the gest if of it is:  new project via cakephp3 skeleton, then cake-admin, then cake-user. admin works great but user runs default user code not manager-user code.  I just assumed it would work out of box for a simple starting point.  is there a cakephp3 skeleton that has cake-admin and cake-users together?  then it be easier for us newbies to work in users pages under/within that layer.

**Comment by bobmulder** [comment]
No there is none... I can take a look to define a tutorial maybe...
